# Generated by Django 4.1.7 on 2023-03-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created timestamp"
                    ),
                ),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "url_id",
                    models.CharField(
                        default="", max_length=15, verbose_name="Short URL"
                    ),
                ),
            ],
            options={
                "verbose_name": "Url",
                "verbose_name_plural": "Urls",
                "ordering": ["-created_timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["url_id"], name="shortener_u_url_id_4e41d2_idx"),
        ),
    ]
